### ISSUE TITLE
Create an etcd provider 

### ISSUE THREAD

**Issue by gifflen** [rackerlabs/simpl#7]
Offer an etcd provider to pull config values during the normal parsing. 

From @hhoover :

http://python-etcd.readthedocs.org/en/latest/

Maybe try etcd and fall back to env vars or config file? Or vice versa?

Example: thinking...
Fabric to seed things:
`client.write('/services/app/APP_CACHE_CONNECTION_STRING ', redis://:secret@redis.example.com:6379/0, ttl=30)`

Checkmate code would read it out:
`client.read('/services/app/APP_CACHE_CONNECTION_STRING').value`

**Comment by gifflen** [comment]
closed won't implement

**Comment by gifflen** [comment]
@hhoover Did you still need this

**Comment by hhoover** [comment]
Yeah, obviously. Please reopen for another 7 years
